### ISSUE TITLE
Publish function can only return a Cursor or an array of Cursors

### ISSUE THREAD

**Issue by alxAgu** [numtel/meteor-pg-leaderboard#1]
Hi, I keep getting the following error:

_"Publish function can only return a Cursor or an array of Cursors."_

Postgres 9.4.4

server.js

```
var LivePg = Meteor.npmRequire('pg-live-select');
var liveDb = new LivePg('MY_CONNECTION_STRING', 'channelx');
Meteor.publish('people', function(){
  return liveDb.select('SELECT id, name FROM person ORDER BY id DESC');
});
```

client.js

```
person = new PgSubscription('people');
Template.hello.helpers({
  person: function(){
    return person.reactive();
  }
});
```

Any ideas of what I may be doing wrong?

**Comment by numtel** [comment]
You do not need to include the NPM package directly. With the numtel:pg Meteor package, you already have the LivePg object available. This object has been modified to work as a cursor that can be published.

**Comment by alxAgu** [comment]
Brilliant! It's working now. 

Thanks.
